import LinkedList from "./LinkedList.js";
const list = new LinkedList();
list.addFirst(1);
list.addLast(2);
list.addLast(3);
list.addLast(4);
list.addLast(5);
list.addLast(6);
list.addLast(7);
list.addLast(8);
list.addLast(9);
list.addLast(10);
list.addLast(11);

// list.removeFirst();
// list.removeLast();
// list.removeLast();
// list.reverse();
// console.log(list.size());
// console.log(list.contains(1));
// console.log(list.toArray());
// console.log(list.kthNodeFromEnd(7));
list.printMiddle();
